[package]
name = "chicane"
version = "0.1.0"
authors = ["aliphe <matthias.alif@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "^0.21.4"
